# Site
name: "Aidan Blog"
title: "Aidan Blog"
description: "aidan blog is personal website of wildan fauzy (@wilfauzy)
  tulisan coretan."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: https://aidanblog.com
google_analytics: 'UA-182162153-1'
disqus: 'idanblog'
mailchimp-list: 'https://wildanfauzy.us10.list-manage.com/subscribe/post?u=72d29580a7ee388212e8622a5&id=f06aca7400'
include: ["_pages"]
permalink: /:title/
email: me@wildanfauzy.com

# Authors
authors:
  Wildan Fauzy:
    name: Wildan Fauzy
    display_name: Wildan Fauzy
    gravatar: 0d6d05efa3831164ebb9a3995e82e9ad
    email: me@wildanfauzy.com
    web: https://a.idan.my.id
    twitter: https://twitter.com/wilfauzy
    description: "Hi, Saya Wildan Fauzy, panggil saja idan atau aidan"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page/:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
